name: audit_anomaly_analyse
channels:
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - anyio=4.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - boto3=1.34.82
  - botocore=1.34.82
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - idna=3.7
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxgboost=2.0.3
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.3.0
  - openpyxl=3.1.2
  - openssl=3.0.14
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=3.10.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=2.0.3
  - pybind11-abi=4
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - s3transfer=0.10.1
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.43.0
  - xgboost=2.0.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - altair==5.3.0
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - astor==0.8.1
      - astunparse==1.6.3
      - backoff==2.2.1
      - blinker==1.8.2
      - cachetools==5.3.3
      - click==8.1.7
      - cloudpickle==3.0.0
      - dateutils==0.6.12
      - duckdb==0.10.1
      - flatbuffers==24.3.25
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - gw-dsl-parser==0.1.48a3
      - h5py==3.11.0
      - ipywidgets==8.1.2
      - jupyterlab-widgets==3.0.10
      - kanaries-track==0.0.4
      - keras==3.4.1
      - libclang==18.1.1
      - llvmlite==0.43.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - monotonic==1.6
      - namex==0.0.8
      - numba==0.60.0
      - opt-einsum==3.3.0
      - optree==0.12.1
      - protobuf==4.25.3
      - pyarrow==16.0.0
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pydeck==0.9.0
      - pygwalker==0.4.8.3
      - rich==13.7.1
      - scikeras==0.13.0
      - segment-analytics-python==2.2.3
      - shap==0.46.0
      - slicer==0.0.8
      - smmap==5.0.1
      - sqlalchemy==2.0.30
      - sqlglot==23.14.0
      - streamlit==1.34.0
      - tenacity==8.3.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - toml==0.10.2
      - toolz==0.12.1
      - tqdm==4.66.5
      - types-python-dateutil==2.9.0.20240316
      - wasmtime==12.0.0
      - watchdog==4.0.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
